custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "{{cloud_node_type_id}}"

# please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "{{project_name}}-train-score"
        <<:
          - *basic-static-cluster
        spark_python_task:
          python_file: "file://{{package}}/entrypoint.py"
          parameters: ["--conf-file", "file:fuse://conf/{{model}}_conf.yml"]
      - name: "{{project_name}}-integration-test"
        <<:
          - *basic-static-cluster
        spark_python_task:
          python_file: "file://tests/integration/{{model}}_train_score_test.py"
          parameters: ["--conf-file", "file:fuse://conf/{{model}}_conf.yml"]
